function g = grad(x,y)
%GRAD
%    G = GRAD(X,Y)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    12-Jun-2018 20:11:38

t2 = x+1.0;
t3 = y+1.0;
t4 = x.*2.0;
t5 = x.^2;
t6 = y.^2;
t7 = t3.^2;
t8 = -t5-t7;
t9 = exp(t8);
t10 = x-1.0;
t11 = -t5-t6;
t12 = exp(t11);
t13 = t6.^2;
t14 = t2.^2;
t15 = -t6-t14;
t16 = exp(t15);
t17 = t10.^2;
t18 = t5.*x.*1.0e1;
t19 = t13.*y.*1.0e1;
t20 = -t4+t18+t19;
g = [t12.*(t5.*3.0e1-2.0)+t9.*(t4-2.0).*3.0+t16.*(t4+2.0).*(1.0./3.0)-t9.*t17.*x.*6.0-t12.*t20.*x.*2.0;t12.*t13.*5.0e1+t16.*y.*(2.0./3.0)-t9.*t17.*(y.*2.0+2.0).*3.0-t12.*t20.*y.*2.0];
